#!/bin/sh

# Скрипт определения имени хоста,  который был последним ведущим.
#
# Данная программа  является  свободным программным обеспечением.
# Вы можете  распространять  и/или  модифицировать  её  согласно
# условиям Стандартной Общественной Лицензии GNU, опубликованной
# Фондом Свободного Программного Обеспечения,  версии 3 или,  по
# Вашему желанию,  любой  более поздней  версии.  Эта  программа
# распространяется в надежде,  что она будет полезной,  но  БЕЗО
# ВСЯКИХ  ГАРАНТИЙ,  в  том  числе,   подразумеваемых   гарантий
# ТОВАРНОГО СОСТОЯНИЯ ПРИ ПРОДАЖЕ  и  ГОДНОСТИ ДЛЯ ОПРЕДЕЛЁННОГО
# ПРИМЕНЕНИЯ. Смотрите Стандартную Общественную Лицензию GNU для
# получения  дополнительной  информации.    Копия  оригинального
# текста  Стандартной  Общественной  Лицензии  GNU  поставляется
# вместе с этой программой в файле LICENSE.
#
# Copyright (C) 2014 Leonid Krivoshein <klark.devel@gmail.com>
#

AUTOSAVEDIR="/home/firebird"
test "x"`/usr/bin/id -u 2>/dev/null` = "x0" || exit 1
if [ -d "$AUTOSAVEDIR" -a -x /root/ic-search ] ; then
    LASTMETA=`/root/ic-search -L -v -LP 2>/dev/null | /usr/bin/cut -f1 -d.`
else
    LASTMETA=''
fi
if [ -n "$LASTMETA" -a -r "${AUTOSAVEDIR}/${LASTMETA}.meta" ] ; then
    /usr/bin/awk '{print $1 " " $2 ":" $3 " " $5}' \
		 "${AUTOSAVEDIR}/${LASTMETA}.meta" 2>/dev/null
else
    /bin/grep ' Switching to state: ' /var/log/daemon.log \
		2>/dev/null | /bin/grep ' ucarp\[' | /usr/bin/tail -n5
fi

exit 0
